### PR TITLE
Playlist 

### PR DESCRIPTION
**Pull request by vashnavichauhan1825**
ignore private routes i will do it soon ! (routes are not private yet)

live url:-https://vaspacx-playlist.netlify.app/

### CODE REVIEW

**Review by shashikantmaurya0007 — APPROVED** [review]
code looks good to be merged

**Review by Varu98 — APPROVED** [review]
Nice work on the UI 👍🏻

**Review by ashishkatiyar2404 — APPROVED** [review]
your code is clean and looks good to me you can merge.

**Comment by vashnavichauhan1825** [comment]
Now routes are protected

**Pull request merged**
